# Generated by Django 3.2.10 on 2021-12-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=30)),
                ('album', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
    ]
